urls.py
from django.urls import path
from . import views

app_name = "personalTour"

urlpatterns = [
    path('accomodationmiddle', views.middle_accommodation, name='accomodationMiddle'),
    path("archiveaccommodation", views.archive_accommodation, name="archiveaccommodation"),
    path("singleaccommodation/<int:id>", views.single_accommodation, name="singleaccommodation"),
    path('accommodationreview/<int:id>', views.accommodation_review, name='accommodationreview'),
    path("archivecar", views.archive_car, name="archivecar"),
    path("singlecar/<int:id>", views.single_car, name="singlecar"),
    path('carreview/<int:id>', views.car_review, name='carreview'),
    path('personalcheckout/', views.personaltour_checkout, name='personalCheckout'),
    path('checkoutcar/<int:id>', views.car_order, name='checkoutCar'),
    path('checkoutdelete/<int:id>', views.delete_checkout, name='checkoutDelete'),
]

models.py
from django.db import models
from adminPanel.models import Country, CarMark
from django.core.validators import MaxValueValidator
from registration.models import Account


class Accommodation(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=256)
    description = models.TextField(blank=True, null=True)
    presentation_text = models.TextField(blank=True, null=True)
    destination = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=256)
    price = models.DecimalField(max_digits=50, decimal_places=2, default=0)
    picture1 = models.ImageField(upload_to='images/accomodation', default='images/brand-2.jpg')
    picture2 = models.ImageField(upload_to='images/accomodation', default='images/brand-2.jpg',
                                 null=True, blank=True)
    picture3 = models.ImageField(upload_to='images/accomodation', default='images/brand-2.jpg',
                                 null=True, blank=True)
    video = models.FileField(upload_to="accomodationvideos")
    ACCOMODATION_TYPES = (
        ("1", 'Hotel'),
        ("2", 'Apartment'),
    )
    accommodation_type = models.CharField(max_length=256, choices=ACCOMODATION_TYPES)
    permission = models.BooleanField(default=False, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Accommodation'


class Hotel(models.Model):
    hotel_name = models.ForeignKey(Accommodation, on_delete=models.CASCADE)
    identification_number = models.CharField(max_length=128)
    number_of_rooms = models.IntegerField(default=0)
    WiFi_connection = models.BooleanField(default=False)
    parking = models.BooleanField(default=False)
    bar = models.BooleanField(default=False)
    pool = models.BooleanField(default=False)


class HotelRoom(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    room_number = models.IntegerField()
    price = models.DecimalField(max_digits=50, decimal_places=2, default=0)
    ROOM_TYPES = (
        ('1', 'Independent room'),
        ('2', 'Shared room'),
        ('3', 'Private room'),
    )
    room_type = models.CharField(max_length=256, choices=ROOM_TYPES)
    ROOM_DESCRIPTION = (
        ('1', 'Twin'),
        ('2', 'Double'),
        ('3', 'Triple'),
        ('4', 'Shared'),
    )
    room_description = models.CharField(max_length=256, choices=ROOM_DESCRIPTION)
    family = models.BooleanField(default=False)


class RoomOrder(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    room = models.ForeignKey(HotelRoom, on_delete=models.CASCADE)
    room_order_start_date = models.DateField()
    room_order_end_date = models.DateField()


class RoomCheckout(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    room_checkout = models.ForeignKey(HotelRoom, on_delete=models.CASCADE)


class Apartment(models.Model):
    apartment_name = models.ForeignKey(Accommodation, on_delete=models.CASCADE)
    CHOICE_OF_APARTMENTS = (
        ('1', 'Studio'),
        ('2', 'F1'),
        ('3', 'F2'),
        ('4', 'F3'),
        ('5', 'F4'),
        ('6', 'villa'),
    )
    choice_of_apartment = models.CharField(max_length=256, choices=CHOICE_OF_APARTMENTS)
    capacity = models.PositiveIntegerField(validators=[MaxValueValidator(20)])
    WiFi_connection = models.BooleanField(default=False)
    parking = models.BooleanField(default=False)
    bar = models.BooleanField(default=False)
    pool = models.BooleanField(default=False)
    availability = models.BooleanField(default=True)


class Car(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, blank=True, null=True)
    destination = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    PICK_UP_LOCATION = (
        ('1', 'Airport'),
        ('2', 'Hotel'),
        ('3', 'Agency'),
    )
    pick_up_location = models.CharField(max_length=256, choices=PICK_UP_LOCATION)
    pick_up_destination = models.CharField(max_length=256, default="")
    CAR_TYPES = (
        ('1', 'Coupe'),
        ('2', 'Sedan'),
        ('3', 'Van'),
    )
    car_types = models.CharField(max_length=256, choices=CAR_TYPES)
    mark = models.ForeignKey(to='adminPanel.CarMark', on_delete=models.SET_NULL, null=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=50, decimal_places=2)
    number_of_sits = models.SmallIntegerField()
    picture1 = models.ImageField(upload_to='images/cars', default='images/brand-2.jpg')
    picture2 = models.ImageField(upload_to='images/cars', default='images/brand-2.jpg')
    permission = models.BooleanField(default=False)

    def __str__(self):
        return str(self.mark)


class AccommodationReview(models.Model):
    accommodation = models.ForeignKey(Accommodation, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    comment = models.TextField()
    stars = models.SmallIntegerField(default=5)
    permition = models.BooleanField(default=False)
    notification = models.BooleanField(default=False)

    def __str__(self):
        return self.user.email

    class Meta:
        verbose_name_plural = "Accommodation Reviews"


class CarReview(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    comment = models.TextField()
    stars = models.SmallIntegerField(default=5)
    permition = models.BooleanField(default=False)
    notification = models.BooleanField(default=False)

    def __str__(self):
        return self.user.email

    class Meta:
        verbose_name_plural = "Car Reviews"


class AccommodationOrder(models.Model):
    name = models.ForeignKey(Accommodation, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    accomodation_order_start_date = models.DateField()
    accomodation_order_end_date = models.DateField()


class AccomodationCheckout(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    accomodation_id = models.ForeignKey(Accommodation, on_delete=models.CASCADE)


class OrderCar(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    car_order_start_date = models.DateField()
    car_order_end_date = models.DateField()


class RoomPicture(models.Model):
    room = models.ForeignKey(HotelRoom, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='images/accomodation')

templates/personalTour/checkout_car.html
{% extends 'homepage/base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
<style>
  img.card_img {
    width: 66px;
}
.cartpages .cart table tr td {
    text-align: center;
    height: 84px;
    box-shadow: 1px 0px 18px 0px #0000001f;
}
.custom-control-input:checked ~ .custom-control-label::before{
  border-color: #DFB610;
background-color: #DFB610;
}
.themed_product img{
  width: 100%;
}
.description{
  margin-top: 10px;
}
.description p{
  margin-bottom: 5px;
}
.product_inner{
  border-radius: 11px;
display: flex;
box-shadow: 2px 3px 13px 0px #0000000f;
overflow: hidden;
}
ul.list-group.mb-3 {
  margin-top: 22px;
 }
 .order_submit_form {
   margin-top: 20px;
  font-size: 15px;
  font-weight: 500;
  background-color: #DFB610;
  color: #fff;
  padding: 12px 24px;
  border-radius: 5px;
  -webkit-transition: .9s;
  -o-transition: .9s;
  transition: .9s;
}
.order_submit_form:hover{
  color: #fff;
}
.images_pay img{
  width: 42%;
}
.images_pay{
  width: 100%;
  margin-top:25px;
}
.billing_address label{
  margin:10px 0 5px;
}
.billing_address input{
  width: 80%;
}
.product_inner h2{
  padding: 15px 0 0;
  font-size: 18px;
}
.main_checkout{
  box-shadow: 1px 6px 13px 8px #00000012;
  width: 100%;
  margin: 25px auto;
  padding: 30px 10px;
  border-radius: 15px;
}
</style>
    <div class="container">
        <div class="py-5 text-center">
          
          <h2>Checkout Page</h2>
          <p class="lead"></p>
        </div>
        <form action="{% url 'personalTour:chechkoutCar' car.id  %}" method="post" style="padding: 0 25px">
          {% csrf_token %}
        <div class="row main_checkout">
          <div class="col-offset-2 col-md-5 order-md-2 mb-4">
            <h4 class="d-flex justify-content-between align-items-center ">
              <h4 class="mb-3">Your Cart</h4>
              <span class="badge badge-secondary badge-pill cart_number"></span>
            </h4>
      
            <div class="cartpages">
              <div class="cart">
               
                <table style="width: 100%;"></table>

                <div class="row themed_product no-gutters">
                  <div class="product_inner">
                  <div class="col-md-5 no-gutters nopadding">
                    <img src="{{ car.picture1.url }}" alt="">
                  </div>
                  <div class="col-md-7" style="padding-right: 0;">
                    <h2>Tbilisi Golden hotel</h2>
                    <div class="description">
                    <p>Price</p>
                    <span>50$</span>
                    </div>
                  </div>
                  </div>
                </div>
              </div>

            </div>
            <ul class="list-group mb-3">
              
           
            
              <li class="list-group-item d-flex justify-content-between">
                <span>Total (USD)</span>
                <span>$50<strong class="reservation_price"></strong></span>
              </li>
            </ul>
            <div class="terms_condition">
            <input type="checkbox" class="form-group" id="terms_condition">
            <label for="terms_condition">
              I Agree <a href="#">Terms and Condition</a>
            </label>
            </div>
            <button type="submit" class="btn  order_submit_form">Checkout</button>
            <div class="images_pay">
           <img src="{% static 'images/MasterCard_credit_cards_and_Visa_If_you_apply_for_both.jpg' %}" alt="">
           </div>
          </div>
          <div class="col-md-7 order-md-1 billing_address">
            <h4 class="mb-3">Billing address</h4>
           <div class="flex">
             <div >
              {{ form }} 
            </div>
          </div>
          </div>
        </div>
      </form>
        </div>
      
      </div>


{% endblock %}

templates/personalTour/order_pack_personal.html
{% extends 'homepage/base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
<style>
  img.card_img {
    width: 66px;
}
.cartpages .cart table tr td {
    text-align: center;
    height: 84px;
    box-shadow: 1px 0px 18px 0px #0000001f;
}
.custom-control-input:checked ~ .custom-control-label::before{
  border-color: #DFB610;
background-color: #DFB610;
}
.themed_product img{
  width: 100%;
}
.description{
  margin-top: 10px;
}
.description p{
  margin-bottom: 5px;
}
.product_inner{
  border-radius: 11px;
display: flex;
box-shadow: 2px 3px 13px 0px #0000000f;
overflow: hidden;
}
ul.list-group.mb-3 {
  margin-top: 22px;
 }
 .order_submit_form {
   margin-top: 20px;
  font-size: 17px;
  font-weight: 500;
  background-color: #DFB610;
  color: #fff;
  padding: 12px 24px;
  border-radius: 5px;
  -webkit-transition: .9s;
  -o-transition: .9s;
  transition: .9s;
}
.order_submit_form:hover{
  color: #fff;
}
.images_pay img{
  width: 13%;
}
.images_pay{
  width: 100%;
  margin-top:25px;
}
.billing_address label{
  margin:10px 0 5px;
}
.billing_address input{
  width: 80%;
}
.product_inner h2{
  padding: 15px 0 0;
  font-size: 18px;
}
.main_checkout{
  box-shadow: 1px 6px 13px 8px #00000012;
  width: 100%;
  margin: 25px auto;
  padding: 30px 10px;
  border-radius: 15px;
}
</style>
    <div class="container">
        <div class="py-5 text-center">
          
          <h2>Checkout Page</h2>
          <p class="lead"></p>
        </div>
        <form method="POST" action="{% url 'personalTour:personalCheckout' %}" style="padding: 0 25px">
          {% csrf_token %}
          {{ formset.management_form }}
        <div class="row main_checkout">
          <div class=" col-md-12 order-md-2 mb-4">
            <h4 class="d-flex justify-content-between align-items-center ">
              <h4 class="mb-3">Your Cart</h4>
              <span class="badge badge-secondary badge-pill cart_number"></span>
            </h4>
            <h4 class="mb-3">Billing address</h4>
           

            <ul class="list-group mb-3">
              <div class="checkout_pages">
                {% for room, form in room_dict.items %}
                <div class="items" > 
                    <div class="row" style="margin-top:30px;">
                    {% for picture in form.1 %}
                      <div class="col-md-4 left_side"> <img src="{{ picture.picture.url }}"> 
                    {% endfor %}
                     <span class="id_data" style="display:none"> </span>  </div> 
                     <div class="col-md-6 checkfiled">
                      
                      <a href="{% url 'personalTour:checkoutDelete' room.id %}" class="deleteLocalsotrage" ><i class="fas fa-times"></i></a>
                      <!-- <a href="#" class="deleteLocalsotrage" ><i class="fas fa-times"></i></a> -->
                      <div class="cart_tablee">
                
                      </div>
                      
                        <h5 id="test"><input type="hidden"  name="server_id" value="${data.serverid}"> </h5>
                        <div class="description">
                        <div class="column_one">
                         <div class="column_one_inner">
                        <h6>Hotel</h6>
                         <p class="title_room">  {{ room.hotel.hotel_name }}</p>
                          </div>
                          <div class="column_one_inner">
                          <h6>Room Number</h6>
                           <p class="number_room"> {{ room.room_number }} </p>
                          </div>
                          </div>
  
                          </div>
  
  
                      <div class="description">
                        <div class="column_one">
                         <div class="column_one_inner">
                        <h6>Price</h6>
                         <p>  {{ room.price }}</p>
                          </div>
                          <div class="column_one_inner roomtype">
                          <h6>Room Type</h6>
                           <p> {{ room.room_number }} </p>
                          </div>
                          </div>
  
                      </div>
  
                      <div class="description">
                        <div class="column_one">
                         <div class="column_one_inner">
                        <h6>Hotel Address</h6>
                         <p>  {{ room.hotel.hotel_name }}</p>
                          </div>
                          </div>
  
                      </div>
                        
                        <div class="check_field_date">
                          {{ form.0 }}
                        <div>
                          
                         </div>
                          </div> </div>  </div>
             
              <hr>
             {% endfor %}
              <li class="list-group-item d-flex justify-content-between">
                <span>Total(USD)</span>
                <span><strong class="reservation_pricee">{{ total_price }}$</strong></span>
              </li>
            </ul>
            <div class="terms_condition">
            <input required type="checkbox" class="form-group" id="terms_condition">
            <label for="terms_condition">
              I Agree <a href="{% url 'components:privacyPolicy' %}">Terms and Condition</a>
            </label>
            </div>
            <button type="submit" class="btn  order_submit_form">Checkout</button>
            <div class="images_pay">
           <img src="{% static 'images/MasterCard_credit_cards_and_Visa_If_you_apply_for_both.jpg' %}" alt="">
           </div>
          </div>
       
        </div>
      </form>
        </div>

      </div>
      
      <script src="{% static 'js/manual/addtocart.js' %}"></script>
      <script src="{% static 'js/manual/checkoutcart.js' %}"></script>


              
{% endblock %}

templates/personalTour/single_car.html
{% extends 'homepage/base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
<!-- only in thsi page -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css">
<!-- only in thsi page -->

<!-- only in this page 2 -->
    <!-- Fotorama from CDNJS, 19 KB -->

    <link  href="https://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.css" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />

<!-- only in this page 2 -->

    <!-- Tour Details -->
    <div class="spicer_section"></div>
   <section id="single_main_banner">
       <div class="main_color col-lg-9 col-md-12">

            <div class="single_inner">
               <div class="row no-gutters">
                   <div class="left_side col-lg-5">


                         <div class="fotorama"
                            data-height="600"
                            data-nav="thumbs"
                            data-fit="cover">
                         <a href="{{ car.picture1.url }}">
                             <img src="{{ car.picture1.url }}" width="144" height="96"></a>
                         <a href="{{ car.picture2.url }}">
                             <img src="{{ car.picture2.url }}" width="144" height="128"></a>

                       </div>


                       </div>

                   <div class="right_side col-lg-7">
                       <h2>{{ accommodation.name }}</h2>
                       <p>{{ accommodation.description }}</p>
                     <div class="sections">
                         <!-- bedroom -->
                         <div class="section_inner">
                             <i class="fas fa-bed"></i>
                             <h6>Car Type: {{ car.get_car_types_display }}</h6>

                         </div>
                         <!-- kitchen  -->
                         <div class="section_inner">
                            <i class="fas fa-sink"></i>
                             <h6>Pick Up Location: {{ car.get_pick_up_location_display }}</h6>
                         </div>
                         <!-- bathroom -->
                         <div class="section_inner">
                            <i class="fas fa-restroom"></i>
                             <h6>Number Of Sits {{ car.number_of_sits }}</h6>
                             <div class="list_icon">

                         </div>
                     </div>
                   </div>
               </div>

        </div>
       </div>

   </section>
    <!-- endTour Details  -->

   <!-- banner memorey -->
   <section id="banner_memory">
       <div class="container">
           <div class="section_inner">

                <h2>We create memorable experiences  </h2>
                <p>An exquisite luxury hotel, offering old-world charm, opulent colonial-era suites, an excellent choice of restaurants</p>

            </div>
       </div>
   </section>
   <!-- banner memorey -->



    <!-- testimonial carousel -->
    <div class="spicer_section"></div>
    <section id="testimonial carousel">
        <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="owl-carousel client-testimonial-carousel">
                    {% for review in reviews %}
                    {% if review.permition %}
                    <div class="single-testimonial-item">
                        <div class="image">
                        <img src="{% static 'images/PR-021-SI-01_05_12-539.png' %}" alt="">
                        </div>

                            <div class="description">
                                <h6>{{ review.review_name }}</h6>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <p>{{ review.comment }}</p>
                            </div>

                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>

</div>

    </section>
    <div class="spicer_section"></div>
    <!-- testimonial carousel -->
<section id="faq_question">
        <div class="container">
            <div class="Question_inner single_review">
                <h2>{% trans 'Write Review' %}</h2>
                <div class="form_faq">
                    <form action="{% url 'personalTour:carreview' car.id %}" method="Post">
                        {% csrf_token %}

                        <div >
                             <label for="Question">Name</label>
                              <input type="text" class="form-control"  name="review_name" placeholder="Enter your name" >
                            <label for="Question">Your Review</label>
                             <textarea name="comment" class="form-control " id="Question" placeholder="Here you can leave your question"></textarea>
                        </div>
                        <div class="Send">
                            <input type="submit" value="Send">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
<!-- bottom booking -->
<section id="booking_bottom">
    <div class="container" style="height: 100%;">
        <div class="section_inner">
            <div class="Total_cost">
                <p>Total Cost: <span>€ 550</span></p>
            </div>
            <div class="booking"  >
                <a href="{% url 'personalTour:chechkoutCar' car.id %}" id="confirmClickActionElementId">
                   Book Now
                </a>
            </div>
        </div>
    </div>
</section>
<!-- bottom booking -->
    <!-- footer -->
<!-- cart Items -->
<div class="cart_full">
    <section id="cart_items" data-toggle="modal" data-target="#modal_aside_right">
        <div class="inner">
            <p> <i class="fas fa-luggage-cart" style="margin-right:10px"></i><span>2 </span> Items In cart</p>
        </div>
      <!-- Modal -->

    </section>
    <div id="modal_aside_right" class="modal fixed-right fade" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-dialog-aside" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Items In Your Cart</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                <div class="items">
             <div class="row">
                 <div class="col-md-6 left_side">
                     <img src="{% static 'images/BG-About.png' %}" alt="">
                 </div>
                 <div class="col-md-6 right_side">
                     <h5>Tbilisi Grand Hotel</h5>
                     <div class="description">
                         <h6>Price</h6>
                         <p>255 $</p>
                         <h6>Destination</h6>
                         <p>Georgia</p>
                         <h6>Duration</h6>
                         <p>25.12.2020- 30.12.2020</p>
                     </div>
                 </div>
             </div>
             </div>
                <div class="items">
             <div class="row">
                 <div class="col-md-6 left_side">
                     <img src="{% static 'images/BG-About.png' %}" alt="">
                 </div>
                 <div class="col-md-6 right_side">
                     <h5>Tbilisi Grand Hotel</h5>
                     <div class="description">
                         <h6>Price</h6>
                         <p>255 $</p>
                         <h6>Destination</h6>
                         <p>Georgia</p>
                         <h6>Duration</h6>
                         <p>25.12.2020- 30.12.2020</p>
                     </div>
                 </div>
             </div>
             </div>
            </div>
           <div class="modal-footer">

                       <div class="total">
                           <h6>Total: <span>555 $</span></h6>
                       </div>

                       <div class="checkout" >
                           <a href="#">Checkout</a>
                       </div>

                   </div>

           </div>
          </div>
        </div> <!-- modal-bialog .// -->
      </div> <!-- modal.// -->
      </div>
    <!-- cart Items -->


<!-- only in this page -->

<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<!-- fotorama -->

<script src="https://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.js"></script>
<!-- fotorama -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
<script src="{% static 'js/manual/testimonial.js' %}"></script>

<!-- only in this page -->
 
{% endblock %}